### ISSUE TITLE
사용자 전용 페이지 URL

### ISSUE THREAD

**Issue by Elian-bang** [Potenday/Potenday_Back#36]
- 개인의 아이디 생성과 동시에 사용자의 메인 페이지로 초대할 수 있는 링크 생성

주어진 숲 Id 값 등을 조합하여 Base62로 인코딩하면 될 것으로 판단됨.

실제 값 : [호스트]/forest/{id}
URL 형태 : [호스트]/forest/{인코딩된 문자열}
API 요청(조회) : /api/forest/{id}

## Refer

![Image](https://user-images.githubusercontent.com/22147400/227942443-0cfa95b8-f4ea-42cb-9ec5-4b386572dbff.png)

**Comment by bangseongmin** [comment]
구현 완료
